name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Lighthouse CI CLI
        run: npm install -g @lhci/cli@0.7.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run Lighthouse CI
        run: lhci autorun

